# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd43d47ff1b1da8a23432ee91826a690e78d7902e000d66240ba4c97416d6943f842f4ee4475d565c7212cbddbf8d753e1ee9509bde05d3da790d829c6bf351e

test:
  secret_key_base: 4f019f77c311eaca305d3b5704685273ace94023677000607a86f215952d5ff366bd06deb6ce6dcb07ea9f75024f967b8fcf8f4f7aaec04a6d41937fde68801e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
